import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "../../styles/global.scss";
import StoreProvider from "../StoreProvider";
import DashboardHeaderServer from "../components/headers/dashboard/dashboard-header-server";
import 'remixicon/fonts/remixicon.css'

const lato = Lato({ subsets: ["latin"], weight: ['100', '400', '700', '900'] });

export const metadata: Metadata = {
    title: "Eventbrite",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={lato.className}>
                <DashboardHeaderServer />
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
