export const dates = [
  "Today",
  "Tomorrow",
  "This weekend",
  "This week",
  "Next week",
  "This month",
  "Next month",
];
export const price = ["Free", "Paid"];
export const format = [
  "Class",
  "Conference",
  "Festival",
  "Party",
  "Appearance",
  "Attraction",
  "Convention",
  "Expo",
  "Gala",
  "Game",
  "Networking",
  "Performance",
  "Race",
  "Rally",
  "Retreat",
  "Screening",
  "Seminar",
  "Tournament",
  "Tour",
];

export const language = [
  "English",
  "German",
  "Spanish",
  "French",
  "Italian",
  "Dutch",
  "Portuguese",
  "Swedish",
];

export const currency = [
  "U.S. Dollar",
  "Canadian Dollar",
  "Euro",
  "British Pound",
  "Japanese Yen",
  "Australian Dollar",
  "New Zealand Dollar",
  "Swiss Franc",
  "Hong Kong Dollar",
  "Singapore Dollar",
  "Swedish Krona",
  "Danish Krone",
  "Polish Zloty",
  "Norwegian Krone",
  "Hungarian Forint",
  "Czech Koruna",
  "Mexican Pesos",
  "Israeli Shekels",
  "Argentinian Peso",
  "Brazilian Real",
  "Chilean Peso",
  "Malaysian Ringgits",
  "Philippine Pesos",
  "Taiwan New Dollars",
  "Thai baht",
  "Turkish Lira",
];
